
# Post \#68500472 [Link](https://stackoverflow.com/questions/68500472/)

## SolidWorks API SelectByID2 method

**Vote**: 2 (631/702) **Views**: 2562 (587/702) 

**Internal ID** \#3-15-638

Created at 2021-07-23 14:03:41

Tags: `vba` `api` `solidworks`

----------

#### Metadata:

Area: `Mobile and Desktop Apps`

Language: `vba` (full parsed tag list: `vba`)

----------

**Notepad**


----------

There is a more efficient method using the  and  methods to obtain the points that can be used with SelectByID2 method. The issue of the method below is that creation of each point is not time efficient nor tidy in the feature tree. Will update this thread once I have time.
Thank you for understanding.

---


I recently started some programming in VBA in SolidWorks and I am looking to write a macro. The goal for now is to create a reference plane from selected face and point(deriving it from edge). As a reminder, method to create the reference plane is InsertRefPlane, which requires the selection to be done by SelectByID2 method.
So far I've managed to save the handle for the face and point objects, but I haven't managed to successfully use the SelectByID2 method. Objects that were selected become deselected.
`value = instance.SelectByID2(Name, Type, X, Y, Z, Append, Mark, Callout, SelectOption)`
I have tried select just a face, but I couldn't manage to do it. Also, I have renamed the face property using the SetEntityName method, and supplied it as well, but it did not manage to select it.
Could you please share the ideas how to do create a reference plane? It doesn't have to be necessary a face and an edge/mid-point.
Thank you in advance.

For further clarification, I have added two objects (face and edge) to selection and I would like to use those to properly select objects with SelectByID2 to use for InsertRefPlane. I have added the code below.
Ideas that I have are:
- I have handles to the face and the edge, but can I use those for proper selection with SelectByID2?- Can I create a reference points on the selected face and edge to identify the face somehow?- SelectByRay seems feasible, but it would require some calculations with face normals so, I would try some other "simpler" methods if available. : I have non-planar face so I can't request Normal property of the face.- : It seems that it all comes down to identifying an object name and type is the way to solve the problem. This is probably a solution, but I'm open for another one, easier if possible. We can create a reference points when using one of appropriate Selection methods, because their names are known, we can use those for SelectbyID2 method.  Will post the solution once I am done.- Regarding the GetFaces/GetFirstFace/GetNextFace methods, [InsertRefPlane](https://help.solidworks.com/2017/english/api/sldworksapi/solidworks.interop.sldworks%7Esolidworks.interop.sldworks.ifeaturemanager%7Einsertrefplane.html) requires objects to be selected by SelectByID2
```
Dim swApp As SldWorks.SldWorks
Dim swModel As SldWorks.ModelDoc2
Dim swPart As SldWorks.PartDoc
Dim swSelMgr As SldWorks.SelectionMgr
Dim swModelDocExt As SldWorks.ModelDocExtension
Dim swFeatMgr As SldWorks.FeatureManager

Dim selBool As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks
Set swModel = swApp.ActiveDoc
Set swModelDocExt = swModel.Extension
Set swPart = swModel
Set swSelMgr = swModel.SelectionManager
Set swFeatMgr = swModel.FeatureManager

' Check which file is opened
Dim filePath As String: filePath = swModel.GetPathName()
Debug.Print "File path is:" & filePath

'   User has to select the face and the edge of the body to create plane and
'   sketch to convert face entities
' Gets selection from SelectionManager
Dim numSelectedObjs As Long
Dim selectionMark As Long: selectionMark = -1

numSelectedObjs = swSelMgr.GetSelectedObjectCount2(selectionMark)
Debug.Print "Number of selected objects:" & numSelectedObjs

Dim faceObj As SldWorks.Face2
Dim edgeObj As SldWorks.Edge
Dim midpointObj As Object

If (numSelectedObjs > 0) Then
    ' Get and validate selection
    Dim selObj As Object
    Dim selObjIndex As Long
    Dim selObjType As Long
    For selObjIndex = 1 To numSelectedObjs ' This method uses 1 as first index
        selObjType = swSelMgr.GetSelectedObjectType3(selObjIndex, selectionMark)
        ' Check selected object type and assign it to appropriate variable
        If (selObjType = SwConst.swSelFACES) Then
            Set faceObj = swSelMgr.GetSelectedObject6(selObjIndex, selectionMark)
            Dim faceFeat As Object
            Set faceFeat = faceObj.GetFeature()
        ElseIf (selObjType = SwConst.swSelEDGES) Then
            Set edgeObj = swSelMgr.GetSelectedObject6(selObjIndex, selectionMark)
            swModel.SelectMidpoint ' With this line, we add point to selection, increasing the count to 3
            Dim deselVal As Long
            deselVal = swSelMgr.DeSelect2(selObjIndex, selectionMark) ' Deselect the edge
            Set midpointObj = swSelMgr.GetSelectedObject6(selObjIndex, selectionMark) ' Set the object to the point
        Else
            MsgBox "Wrong objects selected, select only face and edge"
            Exit For
        End If
    Next
End If

' Create reference plane using face and a point
' InsertRefPlane method requires selection using SelectByID2 Method

Dim objName, objType As String: objName = "": objType = SwConst.swSelectType_e.swSelFACES
Dim X, Y, Z As Double: X = 0: Y = 0: Z = 0
Dim selAppend As Boolean: selAppend = True
Dim objMark As Long: objMark = 0
Dim objCallout As Callout
Dim selOption As swSelectOption_e: selOption = 0

selBool = swModel.Extension.SelectByID2(objName, objType, X, Y, Z, selAppend, objMark, objCallout, selOption)
Debug.Print selBool
```



----------
        
## GPT3.5 Attempt \#0

To create a reference plane using a selected face and point, you can use the following steps:

1. Get the handle for the selected face and point objects.
2. Create a reference point on the selected edge using the `CreatePoint` method of the `ModelDocExtension` object.
3. Use the `SelectByID2` method to select the face and point objects.
4. Use the `InsertRefPlane` method of the `FeatureManager` object to create the reference plane.

Here is the updated code:

```
Dim swApp As SldWorks.SldWorks
Dim swModel As SldWorks.ModelDoc2
Dim swPart As SldWorks.PartDoc
Dim swSelMgr As SldWorks.SelectionMgr
Dim swModelDocExt As SldWorks.ModelDocExtension
Dim swFeatMgr As SldWorks.FeatureManager

Dim selBool As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks
Set swModel = swApp.ActiveDoc
Set swModelDocExt = swModel.Extension
Set swPart = swModel
Set swSelMgr = swModel.SelectionManager
Set swFeatMgr = swModel.FeatureManager

' Check which file is opened
Dim filePath As String: filePath = swModel.GetPathName()
Debug.Print "File path is:" & filePath

'   User has to select the face and the edge of the body to create plane and
'   sketch to convert face entities
' Gets selection from SelectionManager
Dim numSelectedObjs As Long
Dim selectionMark As Long: selectionMark = -1

numSelectedObjs = swSelMgr.GetSelectedObjectCount2(selectionMark)
Debug.Print "Number of selected objects:" & numSelectedObjs

Dim faceObj As SldWorks.Face2
Dim edgeObj As SldWorks.Edge
Dim midpointObj As Object

If (numSelectedObjs > 0) Then
    ' Get and validate selection
    Dim selObj As Object
    Dim selObjIndex As Long
    Dim selObjType As Long
    For selObjIndex = 1 To numSelectedObjs ' This method uses 1 as first index
        selObjType = swSelMgr.GetSelectedObjectType3(selObjIndex, selectionMark)
        ' Check selected object type and assign it to appropriate variable
        If (selObjType = SwConst.swSelFACES) Then
            Set faceObj = swSelMgr.GetSelectedObject6(selObjIndex, selectionMark)
            Dim faceFeat As Object
            Set faceFeat = faceObj.GetFeature()
        ElseIf (selObjType = SwConst.swSelEDGES) Then
            Set edgeObj = swSelMgr.GetSelectedObject6(selObjIndex, selectionMark)
            midpointObj = swModelDocExt.CreatePoint(edgeObj.GetStartVertex().GetPoint())
        Else
            MsgBox "Wrong objects selected, select only face and edge"
            Exit For
        End If
    Next
End If

' Select the face and point objects
Dim faceName As String: faceName = faceObj.GetNameForSelection()
Dim pointName As String: pointName = midpointObj.GetNameForSelection()
Dim objType As Long: objType = SwConst.swSelectType_e.swSelFACES + SwConst.swSelectType_e.swSelPOINTS
Dim selAppend As Boolean: selAppend = True
Dim objMark As Long: objMark = 0
Dim objCallout As Callout
Dim selOption As swSelectOption_e: selOption = 0

selBool = swModel.Extension.SelectByID2(faceName, objType, 0, 0, 0, selAppend, objMark, objCallout, selOption)
selBool = swModel.Extension.SelectByID2(pointName, objType, 0, 0, 0, selAppend, objMark, objCallout, selOption)

' Create reference plane using face and a point
swFeatMgr.InsertRefPlane swRefPlaneReference, False, False, False

End Sub
```

In this updated code, we create a reference point on the selected edge using the `CreatePoint` method of the `ModelDocExtension` object. We then use the `GetNameForSelection` method to get the names of the selected face and point objects, and use the `SelectByID2` method to select them. Finally, we use the `InsertRefPlane` method of the `FeatureManager` object to create the reference plane.

--------

## GPT3.5 Attempt \#1

One way to select the face and point using SelectByID2 method is to use their names. You can use the SetEntityName method to rename the face and point objects to a unique name, and then use that name in the SelectByID2 method. Here's an example code snippet:

```
' Rename face and point objects to unique names
faceObj.SetEntityName "MyFace"
midpointObj.SetEntityName "MyPoint"

' Select face and point using their names
Dim faceName As String: faceName = "MyFace"
Dim pointName As String: pointName = "MyPoint"
Dim faceType As Long: faceType = SwConst.swSelFACES
Dim pointType As Long: pointType = SwConst.swSelPOINTS
selBool = swModel.Extension.SelectByID2(faceName, faceType, 0, 0, 0, True, 0, Nothing, 0)
selBool = swModel.Extension.SelectByID2(pointName, pointType, 0, 0, 0, True, 0, Nothing, 0)

' Create reference plane using selected face and point
swFeatMgr.InsertRefPlane swRefPlaneReference, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing,

--------

## GPT3.5 Attempt \#2

To create a reference plane using a selected face and point, you can use the following steps:

1. Get the handle for the selected face and point objects.
2. Create a reference point on the selected face using the AddRefPoint method.
3. Use the SelectByID2 method to select the reference point and the selected edge.
4. Use the InsertRefPlane method to create the reference plane.

Here's an example code snippet that demonstrates this approach:

```
Dim swApp As SldWorks.SldWorks
Dim swModel As SldWorks.ModelDoc2
Dim swSelMgr As SldWorks.SelectionMgr
Dim swModelDocExt As SldWorks.ModelDocExtension
Dim swFeatMgr As SldWorks.FeatureManager

Sub main()

    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    Set swModelDocExt = swModel.Extension
    Set swSelMgr = swModel.SelectionManager
    Set swFeatMgr = swModel.FeatureManager

    ' Get the selected face and point objects
    Dim faceObj As SldWorks.Face2
    Dim pointObj As SldWorks.RefPoint
    Set faceObj = swSelMgr.GetSelectedObject6(1, -1)
    Set pointObj = swSelMgr.GetSelectedObject6(2, -1)

    ' Create a reference point on the selected face
    Dim refPointObj As SldWorks.RefPoint
    Set refPointObj = swFeatMgr.CreateRefPoint(faceObj)

    ' Select the reference point and the selected edge
    Dim selObjName As String
    Dim selObjType As Long
    Dim selX As Double
    Dim selY As Double
    Dim selZ As Double
    Dim selAppend As Boolean
    Dim selMark As Long
    Dim selCallout As SldWorks.Callout
    Dim selOption As SldWorks.swSelectOption_e
    selObjName = refPointObj.GetNameForSelection()
    selObjType = swSelMgr.GetSelectedObjectType3(2, -1)
    selX = pointObj.X
    selY = pointObj.Y
    selZ = pointObj.Z
    selAppend = True
    selMark = 0
    selCallout = Nothing
    selOption = swSelOptions_e.swSelOptionsDefault
    swModel.Extension.SelectByID2 selObjName, selObjType, selX, selY, selZ, selAppend, selMark, selCallout, selOption

    ' Create the reference plane
    Dim refPlaneObj As SldWorks.Feature
    Set refPlaneObj = swFeatMgr.InsertRefPlane(Nothing, Nothing, Nothing, Nothing)

End Sub
```

Note that this approach assumes that the selected point is on the selected edge. If this is not the case, you may need to use a different method to select the edge, such as SelectByRay.

--------
